name: Health Monitoring

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Site
      id: site
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://kariajuda.com
        max-attempts: 3
        retry-delay: 5s
        
    - name: Check API
      id: api
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://api.kariajuda.com/health
        max-attempts: 3
        retry-delay: 5s
        
    - name: Check Admin
      id: admin
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://admin.kariajuda.com
        max-attempts: 3
        retry-delay: 5s

    - name: Send alert if any service is down
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "🚨 Service Down Alert",
            attachments: [{
              color: 'danger',
              text: `One or more services are not responding:
                Site: ${{ steps.site.outcome }}
                API: ${{ steps.api.outcome }}
                Admin: ${{ steps.admin.outcome }}`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Trigger auto-restart if down
      if: failure()
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/kariajuda
          docker-compose restart
          sleep 30
          ./scripts/health_check.sh